### ISSUE TITLE
Add support for Mermaid presenter

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/uml-reverse-mapper#24]
We currently support Graphviz and PlantUML visualizers. A great addition would be Mermaid,
see https://github.com/mermaid-js/mermaid

**Comment by sivasubramanim** [comment]
@iluwatar : Can I work on this?

**Comment by iluwatar** [comment]
Please go ahead @sivasubramanim

**Comment by sivasubramanim** [comment]
@iluwatar : I was tied up with some work and could not work last month. Apologies for the delay.

The pull request contains the change for the issue.I used the below documentation to define the class diagram standards: https://mermaid-js.github.io/mermaid/#/classDiagram

I have also include the changes to ReadMe file and Test file for the new mermaid presenter.

@iluwatar : Please review the changes and let me know your thoughts.
