### ISSUE TITLE
Add Java 11 support

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/uml-reverse-mapper#42]
Currently the project is being built with Java 8. It would be great to upgrade to Java 11. It's easy to set the maven-compiler-version to 11 to compile with newer Java but this breaks the tests and the reason should be investigated.

**Comment by hbothra15** [comment]
HI @iluwatar 

I would like to pick this up. As per my initial analysis, the issue has been introduced by Java 9 changes
https://stackoverflow.com/questions/46694600/java-9-compatability-issue-with-classloader-getsystemclassloader

As mentioned in above link, ClassLoader now no more uses URLClassLoader which we are using at

`DomainClassFinder # findClasses method`

**Comment by iluwatar** [comment]
Ok @hbothra15, go ahead 👍🏻

**Comment by hbothra15** [comment]
Hi @iluwatar Please review #56
