### ISSUE TITLE
Request : showing a config example with a real project (in a video)

### ISSUE THREAD

**Issue by AdinhLux** [iluwatar/uml-reverse-mapper#83]
Hi,

Currently I'm trying to generate the UML file with `mvn clean package` for 2 projects : 

- 1 with Spring Boot.
- 1 with only a main() calling a dummy class.

In both cases I generate a file for `graphviz` `plantuml` and `mermaid` but the content is nearly empty.

Could you please provide us **a video showing how to configure correctly your plugin** with a project (for example a Spring Boot) ?

Thanks a lot.

Alexandre

**Comment by crossworth** [comment]
About the springboot see if this helps https://github.com/iluwatar/uml-reverse-mapper/issues/63#issuecomment-977377006

**Comment by iluwatar** [comment]
Closing as duplicate of #63 and #69
