### ISSUE TITLE
Few queries

### ISSUE THREAD

**Issue by murthy-nn** [iluwatar/uml-reverse-mapper#84]
Thanks for developing the application UML Reverse Mapper. I am looking for a similar application.

I have the following queries. I am using the Issues section, as I did not find any other place to raise them. Appreciate a clarification.

1) I referred to the procedure given in https://java-design-patterns.com/blog/auto-generate-class-diagrams-with-uml-reverse-mapper/ and have generated .uml files. How to open the UML file? Eclipse shows it as an XML file.

2) The app generates Class diagram as documented. What changes are required to auto-generate Sequence diagrams from Java code?

**Comment by iluwatar** [comment]
1) Depending on the configuration, the system generates Graphviz, PlantUML, or Mermaid formatted files and they can be opened with the respective applications.
2) Sequence diagrams haven't been implemented yet, but there is an open issue about it. See #58
