### ISSUE TITLE
URM Successfully Analyzes Project in 1.4.8, Return Empty Files in 2.0.0

### ISSUE THREAD

**Issue by aj-stein-nist** [iluwatar/uml-reverse-mapper#86]
Hello, I am trying to use the current stable release of this tool (as a maven plugin) and weirdly enough it works for 1.4.8 but the PlantUML and Mermaid outputs come out suspiciously empty with 2.0.0. Any ideas on how I can troubleshoot and remedy that?

https://github.com/aj-stein-nist/metaschema-java/tree/iluwatar/uml-reverse-mapper%2386

**Comment by mchs62** [comment]
Hi @aj-stein-nist,
in  the 2.0.0  you have to define he packages in a <depedencies> tag inside the plugin.
